-- MySQL Script generated by MySQL Workbench
-- Tue Dec 13 20:31:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema abrigo_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema abrigo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `abrigo_db` DEFAULT CHARACTER SET latin1 ;
USE `abrigo_db` ;

-- -----------------------------------------------------
-- Table `abrigo_db`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`pessoas` (
  `pess_id` INT NOT NULL AUTO_INCREMENT,
  `pess_nome` VARCHAR(60) NOT NULL,
  `pess_data_nasc` DATE NOT NULL,
  `pess_cpf` VARCHAR(14) NOT NULL,
  `pess_sexo` CHAR(1) NOT NULL,
  `pess_endereco` VARCHAR(45) NOT NULL,
  `pess_bairro` VARCHAR(45) NOT NULL,
  `pess_cidade` VARCHAR(45) NOT NULL,
  `pess_cep` VARCHAR(9) NOT NULL,
  `pess_uf` CHAR(2) NOT NULL,
  PRIMARY KEY (`pess_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`responsaveis_internacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`responsaveis_internacoes` (
  `resp_inte_id` INT NOT NULL AUTO_INCREMENT,
  `resp_inte_pess_id` INT NOT NULL,
  PRIMARY KEY (`resp_inte_id`),
  INDEX `fk_responsavel_internacao_pessoa1_idx` (`resp_inte_pess_id` ASC) VISIBLE,
  CONSTRAINT `fk_responsavel_internacao_pessoa1`
    FOREIGN KEY (`resp_inte_pess_id`)
    REFERENCES `abrigo_db`.`pessoas` (`pess_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`idosos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`idosos` (
  `idos_id` INT NOT NULL AUTO_INCREMENT,
  `idos_pess_id` INT NOT NULL,
  `idos_resp_inte_id` INT NOT NULL,
  `idos_cor` VARCHAR(45) NOT NULL,
  `idos_tipo_sanguineo` CHAR(2) NOT NULL,
  `idos_grau_instrucao` VARCHAR(45) NOT NULL,
  `idos_profissao` VARCHAR(45) NOT NULL,
  `idos_mae` VARCHAR(60) NOT NULL,
  `idos_pai` VARCHAR(60) NOT NULL,
  `idos_data_ingresso` DATE NOT NULL,
  `idos_religiao` VARCHAR(45) NOT NULL,
  `idos_batizado` TINYINT(1) NOT NULL,
  `idos_estd_civil` VARCHAR(45) NOT NULL,
  `idos_casm_relig` TINYINT(1) NOT NULL,
  `idos_mant_familia` TINYINT(1) NOT NULL,
  `idos_qtde_filhos` INT NOT NULL,
  `idos_tem_bens` TINYINT(1) NOT NULL,
  `idos_livre_espo_vontd` TINYINT(1) NOT NULL,
  `idos_pertences` TEXT NOT NULL,
  `idos_inter_ord_jud` TINYINT(1) NOT NULL,
  `idos_eleitor` TINYINT(1) NOT NULL,
  `idos_valor_contribuicao` FLOAT NOT NULL,
  `idos_falecido` TINYINT(1) NOT NULL,
  `idos_reinc_familia` TINYINT(1) NOT NULL,
  `idos_ativo` TINYINT(1) NOT NULL,
  `idos_sus_municipal` CHAR(5) NOT NULL,
  `idos_sus_nacional` CHAR(18) NOT NULL,
  PRIMARY KEY (`idos_id`),
  INDEX `fk_idoso_pessoa_idx` (`idos_pess_id` ASC) VISIBLE,
  INDEX `fk_idoso_responsavel_internacao1_idx` (`idos_resp_inte_id` ASC) VISIBLE,
  CONSTRAINT `fk_idoso_pessoa`
    FOREIGN KEY (`idos_pess_id`)
    REFERENCES `abrigo_db`.`pessoas` (`pess_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idoso_responsavel_internacao1`
    FOREIGN KEY (`idos_resp_inte_id`)
    REFERENCES `abrigo_db`.`responsaveis_internacoes` (`resp_inte_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`documentos` (
  `docu_id` INT NOT NULL AUTO_INCREMENT,
  `docu_regi_casamento` TINYINT(1) NOT NULL,
  `docu_regi_nascimento` TINYINT(1) NOT NULL,
  `docu_identidade` TINYINT(1) NOT NULL,
  `docu_idoso_id` INT NOT NULL,
  `docu_cart_trab` TINYINT(1) NOT NULL,
  `docu_titulo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`docu_id`),
  INDEX `fk_documentos_idoso1_idx` (`docu_idoso_id` ASC) VISIBLE,
  CONSTRAINT `fk_documentos_idoso1`
    FOREIGN KEY (`docu_idoso_id`)
    REFERENCES `abrigo_db`.`idosos` (`idos_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`carteiras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`carteiras` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `cart_numero` VARCHAR(15) NOT NULL,
  `cart_serie` VARCHAR(15) NOT NULL,
  `cart_docu_id` INT NOT NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `fk_carteira_documentos1_idx` (`cart_docu_id` ASC) VISIBLE,
  CONSTRAINT `fk_carteira_documentos1`
    FOREIGN KEY (`cart_docu_id`)
    REFERENCES `abrigo_db`.`documentos` (`docu_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`titulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`titulos` (
  `titu_id` INT NOT NULL AUTO_INCREMENT,
  `titu_numero` VARCHAR(20) NOT NULL,
  `titu_zona` VARCHAR(10) NOT NULL,
  `titu_secao` VARCHAR(10) NOT NULL,
  `titu_docu_id` INT NOT NULL,
  PRIMARY KEY (`titu_id`),
  INDEX `fk_titulo_documentos1_idx` (`titu_docu_id` ASC) VISIBLE,
  CONSTRAINT `fk_titulo_documentos1`
    FOREIGN KEY (`titu_docu_id`)
    REFERENCES `abrigo_db`.`documentos` (`docu_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`exames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`exames` (
  `exam_id` INT NOT NULL AUTO_INCREMENT,
  `exam_rx_torax` TINYINT(1) NOT NULL,
  `exam_pa` TINYINT(1) NOT NULL,
  `exam_contagioso` TINYINT(1) NOT NULL,
  `exam_hemo_completo` TINYINT(1) NOT NULL,
  `exam_ecg` TINYINT(1) NOT NULL,
  `exam_soro_lues` TINYINT(1) NOT NULL,
  `exam_urina` TINYINT(1) NOT NULL,
  `exam_fezes` TINYINT(1) NOT NULL,
  `exam_receitas` TINYINT(1) NOT NULL,
  `exam_decl_medica` TINYINT(1) NOT NULL,
  `exam_idoso_id` INT NOT NULL,
  PRIMARY KEY (`exam_id`),
  INDEX `fk_exames_idoso1_idx` (`exam_idoso_id` ASC) VISIBLE,
  CONSTRAINT `fk_exames_idoso1`
    FOREIGN KEY (`exam_idoso_id`)
    REFERENCES `abrigo_db`.`idosos` (`idos_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`identidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`identidades` (
  `iden_id` INT NOT NULL AUTO_INCREMENT,
  `iden_numero` VARCHAR(12) NOT NULL,
  `iden_orgao` VARCHAR(45) NOT NULL,
  `iden_docu_id` INT NOT NULL,
  PRIMARY KEY (`iden_id`),
  INDEX `fk_identidade_documentos1_idx` (`iden_docu_id` ASC) VISIBLE,
  CONSTRAINT `fk_identidade_documentos1`
    FOREIGN KEY (`iden_docu_id`)
    REFERENCES `abrigo_db`.`documentos` (`docu_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`responsaveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`responsaveis` (
  `resp_id` INT NOT NULL AUTO_INCREMENT,
  `resp_pess_id` INT NOT NULL,
  `resp_identidade` CHAR(12) NOT NULL,
  `resp_telefone` VARCHAR(15) NOT NULL,
  `resp_telefones` VARCHAR(15) NULL,
  PRIMARY KEY (`resp_id`),
  INDEX `fk_responsavel_pessoa1_idx` (`resp_pess_id` ASC) VISIBLE,
  CONSTRAINT `fk_responsavel_pessoa1`
    FOREIGN KEY (`resp_pess_id`)
    REFERENCES `abrigo_db`.`pessoas` (`pess_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`receitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`receitas` (
  `rece_id` INT NOT NULL AUTO_INCREMENT,
  `rece_idos_id` INT NOT NULL,
  `rece_medico` VARCHAR(60) NOT NULL,
  `rece_data` DATE NOT NULL,
  `rece_ativa` TINYINT(1) NOT NULL,
  PRIMARY KEY (`rece_id`),
  INDEX `fk_receita_idoso1_idx` (`rece_idos_id` ASC) VISIBLE,
  CONSTRAINT `fk_receita_idoso1`
    FOREIGN KEY (`rece_idos_id`)
    REFERENCES `abrigo_db`.`idosos` (`idos_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`medicamentos` (
  `medc_id` INT NOT NULL AUTO_INCREMENT,
  `medc_horario` VARCHAR(45) NULL,
  `medc_rece_id` INT NOT NULL,
  `medc_nome` VARCHAR(45) NOT NULL,
  `medc_ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`medc_id`),
  INDEX `fk_medicamento_receita1_idx` (`medc_rece_id` ASC) VISIBLE,
  CONSTRAINT `fk_medicamento_receita1`
    FOREIGN KEY (`medc_rece_id`)
    REFERENCES `abrigo_db`.`receitas` (`rece_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`colaboradores` (
  `cola_id` INT NOT NULL AUTO_INCREMENT,
  `cola_pess_id` INT NOT NULL,
  `cola_telefone` VARCHAR(12) NOT NULL,
  `cola_identidade` VARCHAR(12) NOT NULL,
  `cola_funcao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cola_id`),
  INDEX `fk_colaborador_pessoa1_idx` (`cola_pess_id` ASC) VISIBLE,
  CONSTRAINT `fk_colaborador_pessoa1`
    FOREIGN KEY (`cola_pess_id`)
    REFERENCES `abrigo_db`.`pessoas` (`pess_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`funcionarios` (
  `func_id` INT NOT NULL AUTO_INCREMENT,
  `func_cola_id` INT NOT NULL,
  `func_carg_horaria` VARCHAR(45) NOT NULL,
  `func_salario` VARCHAR(45) NULL,
  `func_faltas` VARCHAR(2000) NULL,
  PRIMARY KEY (`func_id`),
  INDEX `fk_funcionario_colaborador1_idx` (`func_cola_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_colaborador1`
    FOREIGN KEY (`func_cola_id`)
    REFERENCES `abrigo_db`.`colaboradores` (`cola_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`voluntarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`voluntarios` (
  `volu_id` INT NOT NULL AUTO_INCREMENT,
  `volu_cola_id` INT NOT NULL,
  `volu_comprometimento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`volu_id`),
  INDEX `fk_voluntario_colaborador1_idx` (`volu_cola_id` ASC) VISIBLE,
  CONSTRAINT `fk_voluntario_colaborador1`
    FOREIGN KEY (`volu_cola_id`)
    REFERENCES `abrigo_db`.`colaboradores` (`cola_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`obitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`obitos` (
  `obit_id` INT NOT NULL AUTO_INCREMENT,
  `obit_idoso_id` INT NOT NULL,
  `obit_causa` VARCHAR(45) NOT NULL,
  `obit_local` VARCHAR(45) NOT NULL,
  `obit_extre_uncao` TINYINT(1) NOT NULL,
  `obit_data_falecimento` DATE NOT NULL,
  PRIMARY KEY (`obit_id`),
  INDEX `fk_obitos_idoso1_idx` (`obit_idoso_id` ASC) VISIBLE,
  CONSTRAINT `fk_obitos_idoso1`
    FOREIGN KEY (`obit_idoso_id`)
    REFERENCES `abrigo_db`.`idosos` (`idos_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`esperas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`esperas` (
  `espe_id` INT NOT NULL AUTO_INCREMENT,
  `espe_pess_id` INT NOT NULL,
  `espe_situacao` VARCHAR(60) NOT NULL,
  `espe_pedinte` VARCHAR(60) NOT NULL,
  `espe_tele_pedinte` VARCHAR(45) NOT NULL,
  `espe_data_pedido` DATE NOT NULL,
  `espe_anal_prioridade` TEXT NULL,
  `espe_nive_prioridade` INT NULL,
  PRIMARY KEY (`espe_id`),
  INDEX `fk_espera_pessoa1_idx` (`espe_pess_id` ASC) VISIBLE,
  CONSTRAINT `fk_espera_pessoa1`
    FOREIGN KEY (`espe_pess_id`)
    REFERENCES `abrigo_db`.`pessoas` (`pess_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`pedidos_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`pedidos_servicos` (
  `pedi_id` INT NOT NULL AUTO_INCREMENT,
  `pedi_pess_id` INT NOT NULL,
  `pedi_tipo_servico` VARCHAR(45) NOT NULL,
  `pedi_telefone` VARCHAR(45) NOT NULL,
  `pedi_ende_referencia` VARCHAR(45) NULL,
  `pedi_date` DATE NOT NULL,
  `pedi_email` VARCHAR(45) NULL,
  PRIMARY KEY (`pedi_id`),
  INDEX `fk_pediodo_pessoa1_idx` (`pedi_pess_id` ASC) VISIBLE,
  CONSTRAINT `fk_pediodo_pessoa1`
    FOREIGN KEY (`pedi_pess_id`)
    REFERENCES `abrigo_db`.`pessoas` (`pess_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`visitantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`visitantes` (
  `visi_id` INT NOT NULL AUTO_INCREMENT,
  `visi_telefone` VARCHAR(45) NULL,
  `visi_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`visi_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`idoso_reinceridos_familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`idoso_reinceridos_familia` (
  `reic_id` INT NOT NULL AUTO_INCREMENT,
  `reic_data` DATE NOT NULL,
  `reic_motivo` VARCHAR(60) NOT NULL,
  `reic_idos_id` INT NOT NULL,
  PRIMARY KEY (`reic_id`),
  INDEX `fk_idoso_reinceridos_familia_idoso1_idx` (`reic_idos_id` ASC) VISIBLE,
  CONSTRAINT `fk_idoso_reinceridos_familia_idoso1`
    FOREIGN KEY (`reic_idos_id`)
    REFERENCES `abrigo_db`.`idosos` (`idos_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`atendimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`atendimentos` (
  `aten_id` INT NOT NULL AUTO_INCREMENT,
  `aten_tipo` VARCHAR(45) NOT NULL,
  `aten_prof_nome` VARCHAR(45) NOT NULL,
  `aten_data` DATE NOT NULL,
  `aten_procedimento` TEXT NULL,
  `aten_idos_id` INT NOT NULL,
  PRIMARY KEY (`aten_id`),
  INDEX `fk_atendimentos_idoso1_idx` (`aten_idos_id` ASC) VISIBLE,
  CONSTRAINT `fk_atendimentos_idoso1`
    FOREIGN KEY (`aten_idos_id`)
    REFERENCES `abrigo_db`.`idosos` (`idos_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`eventos` (
  `even_id` INT NOT NULL AUTO_INCREMENT,
  `even_tipo` VARCHAR(45) NOT NULL,
  `even_data` VARCHAR(45) NOT NULL,
  `even_local` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`even_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`doencas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`doencas` (
  `doen_id` INT NOT NULL AUTO_INCREMENT,
  `doen_nome_popular` VARCHAR(45) NULL,
  `doen_cientifico` VARCHAR(45) NOT NULL,
  `doen_codigo` INT NULL,
  PRIMARY KEY (`doen_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`idosos_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`idosos_eventos` (
  `idos_even_id` INT NOT NULL AUTO_INCREMENT,
  `idos_even_even_id` INT NOT NULL,
  `idos_even_idos_id` INT NOT NULL,
  PRIMARY KEY (`idos_even_id`),
  INDEX `fk_idosos_eventos_eventos1_idx` (`idos_even_even_id` ASC) VISIBLE,
  INDEX `fk_idosos_eventos_idosos1_idx` (`idos_even_idos_id` ASC) VISIBLE,
  UNIQUE INDEX `idosos_eventos_UNIQUE` (`idos_even_even_id` ASC, `idos_even_idos_id` ASC) VISIBLE,
  CONSTRAINT `fk_idosos_eventos_eventos1`
    FOREIGN KEY (`idos_even_even_id`)
    REFERENCES `abrigo_db`.`eventos` (`even_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idosos_eventos_idosos1`
    FOREIGN KEY (`idos_even_idos_id`)
    REFERENCES `abrigo_db`.`idosos` (`idos_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`idosos_responsaveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`idosos_responsaveis` (
  `idos_resp_id` INT NOT NULL AUTO_INCREMENT,
  `idos_resp_idos_id` INT NOT NULL,
  `idos_resp_resp_id` INT NOT NULL,
  PRIMARY KEY (`idos_resp_id`),
  INDEX `fk_idosos_responsaveis_idosos1_idx` (`idos_resp_idos_id` ASC) VISIBLE,
  INDEX `fk_idosos_responsaveis_responsavel1_idx` (`idos_resp_resp_id` ASC) VISIBLE,
  UNIQUE INDEX `idoso_responsavel_UNIQUE` (`idos_resp_idos_id` ASC, `idos_resp_resp_id` ASC) VISIBLE,
  CONSTRAINT `fk_idosos_responsaveis_idosos1`
    FOREIGN KEY (`idos_resp_idos_id`)
    REFERENCES `abrigo_db`.`idosos` (`idos_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idosos_responsaveis_responsavel1`
    FOREIGN KEY (`idos_resp_resp_id`)
    REFERENCES `abrigo_db`.`responsaveis` (`resp_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`idosos_visitantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`idosos_visitantes` (
  `idos_visi_id` INT NOT NULL AUTO_INCREMENT,
  `idos_visi_visi_id` INT NOT NULL,
  `idos_visi_idos_id` INT NOT NULL,
  `idos_visi_data` DATE NOT NULL,
  `idos_visi_grau_parentesco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idos_visi_id`),
  INDEX `fk_idosos_visitantes_visitantes1_idx` (`idos_visi_visi_id` ASC) VISIBLE,
  INDEX `fk_idosos_visitantes_idosos1_idx` (`idos_visi_idos_id` ASC) VISIBLE,
  UNIQUE INDEX `idosos_visitates_UNIQUE` (`idos_visi_visi_id` ASC, `idos_visi_idos_id` ASC) VISIBLE,
  CONSTRAINT `fk_idosos_visitantes_visitantes1`
    FOREIGN KEY (`idos_visi_visi_id`)
    REFERENCES `abrigo_db`.`visitantes` (`visi_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idosos_visitantes_idosos1`
    FOREIGN KEY (`idos_visi_idos_id`)
    REFERENCES `abrigo_db`.`idosos` (`idos_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`usuarios` (
  `usua_id` INT NOT NULL AUTO_INCREMENT,
  `usua_nome` VARCHAR(45) NOT NULL,
  `usua_login` VARCHAR(45) NOT NULL,
  `usua_senha` VARCHAR(45) NOT NULL,
  `usua_nivel` INT NOT NULL,
  PRIMARY KEY (`usua_id`),
  UNIQUE INDEX `usua_login_UNIQUE` (`usua_login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abrigo_db`.`idosos_doencas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abrigo_db`.`idosos_doencas` (
  `idos_doen_id` INT NOT NULL AUTO_INCREMENT,
  `idos_doen_idos_id` INT NOT NULL,
  `idos_doen_doen_id` INT NOT NULL,
  PRIMARY KEY (`idos_doen_id`),
  INDEX `fk_idosos_doencas_idosos1_idx` (`idos_doen_idos_id` ASC) VISIBLE,
  INDEX `fk_idosos_doencas_doencas1_idx` (`idos_doen_doen_id` ASC) VISIBLE,
  CONSTRAINT `fk_idosos_doencas_idosos1`
    FOREIGN KEY (`idos_doen_idos_id`)
    REFERENCES `abrigo_db`.`idosos` (`idos_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idosos_doencas_doencas1`
    FOREIGN KEY (`idos_doen_doen_id`)
    REFERENCES `abrigo_db`.`doencas` (`doen_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
